location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/Point-LIO
    name: point_lio
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/point_lio
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_point_lio_estimator_plugin
    name: mrs_point_lio_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_point_lio_estimator_plugin
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/Point-LIO
    name: point_lio
    rev: 46d0db70e43fda396a691677ac6882dd79e2946f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/point_lio
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_point_lio_estimator_plugin
    name: mrs_point_lio_estimator_plugin
    rev: 44c36f7a05f5f74aa1ad9c881be9adcdc89f195a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_point_lio_estimator_plugin
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
