location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/Point-LIO
    name: point_lio
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/point_lio
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_point_lio_estimator_plugin
    name: mrs_point_lio_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_point_lio_estimator_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:ctu-mrs/livox_ros_driver2.git
    name: livox_ros_driver2
    rev: local-sdk-install
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/livox_ros_driver2
    scripts:
      - git submodule update --init --recursive
      - cd installation && ./install.sh ROS1
sources_locked:
  - repo: https://github.com/ctu-mrs/Point-LIO
    name: point_lio
    rev: f397ab55a1d9aadfcc02931cc87b55f1e74415b3
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/point_lio
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_point_lio_estimator_plugin
    name: mrs_point_lio_estimator_plugin
    rev: 44c36f7a05f5f74aa1ad9c881be9adcdc89f195a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_point_lio_estimator_plugin
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
